sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t com777/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true com777/docker-react npm run test
